# Generated by Django 3.1.4 on 2020-12-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_keywordmodel_tag_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordmodel',
            name='tag_list',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
